/*
  uuidv5 generates a name-based UUID, as described in RFC 4122 section 4.3, also known as a "version 5" UUID.

  Unlike the pseudo-random UUIDs generated by uuid, name-based UUIDs derive from namespace and an name, producing the same UUID value every time if the namespace and name are unchanged.

Name-based UUID namespaces are themselves UUIDs, but for readability this function accepts some keywords as aliases for the namespaces that were assigned by RFC 4122:



*/

locals {
  url = "www.example.com"
}

output "uuidv5" {
  value = uuidv5("url", local.url)
}
